### ISSUE TITLE
Makefile doesn't include task for World_EEZ_v8_2014.shp

### ISSUE THREAD

**Issue by almccon** [oceanplanning/oceanplanning.org#3]
`make basedata` gives the following error:

```
make: *** No rule to make target `data/World_EEZ_v8_20140228_LR/World_EEZ_v8_2014.shp', needed by `basedata'.  Stop.
```

**Comment by almccon** [comment]
The [download link](http://www.marineregions.org/download_file.php?fn=v8_20140228_LR) at marineregions.org requires a click-through:

![screen shot 2015-07-24 at 1 32 56 pm](https://cloud.githubusercontent.com/assets/1212178/8884070/91acdd5e-3208-11e5-84e4-b0844448b06b.png)

**Comment by almccon** [comment]
Now the makefile gives the following error, prompting the user to download the correct file:

```
Makefile:40: *** Download World_EEZ_v8_20140228_LR.zip from http://www.marineregions.org/download_file.php?fn=v8_20140228_LR and place the zipfile in the oceanplanning.org/data directory. Then try again.  Stop.
```

Does this work for you, @nwehner?

**Comment by nwehner** [comment]
One step closer! 

Now it’s giving me the error (with some proceeding lines for context):

inflating: data/World_EEZ_v8_20140228_LR/World_Maritime_Boundaries_v8.sbn  
ogr2ogr --config SHAPE_ENCODING WINDOWS-1252 --config OGR_ENABLE_PARTIAL_REPROJECTION TRUE -t_srs '+proj=laea +lat_0=40 +lon_0=-105 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs' data/ne_10m_admin_1_states_provinces_lakes_laea.shp data/ne_10m_admin_1_states_provinces_lakes.shp
ERROR 1: data/ne_10m_admin_1_states_provinces_lakes_laea.shp is not a directory.

ESRI Shapefile driver failed to create data/ne_10m_admin_1_states_provinces_lakes_laea.shp
make: **\* [data/ne_10m_admin_1_states_provinces_lakes_laea.shp] Error 1

**Comment by almccon** [comment]
I think that error happens when the shapefile that it's trying to create already exists. I added some `-overwrite` flags to the make tasks, so hopefully that error will go away. I created a few new errors in the process but I think I suppressed those two. Makefiles involving shapefiles are a pain, sorry it's such a mess!

**Comment by nwehner** [comment]
Woot woot! I think it’s working this time. No more error messages. Thank you :)
